# Generated by Django 5.2.18 on 2026-10-07 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VeiculoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('categoria', models.CharField(choices=[('VL', 'Leve'), ('VC', 'Coletivo')], max_length=2)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ReservaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante', models.CharField(max_length=120)),
                ('setor', models.CharField(max_length=80)),
                ('atividade', models.CharField(max_length=120)),
                ('origem', models.CharField(max_length=120)),
                ('destino', models.CharField(max_length=120)),
                ('data', models.DateField()),
                ('saida', models.TimeField()),
                ('retorno', models.TimeField()),
                ('passageiros', models.PositiveSmallIntegerField()),
                ('categoria_pretendida', models.CharField(blank=True, choices=[('VL', 'Leve'), ('VC', 'Coletivo')], max_length=2)),
                ('observacoes', models.TextField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='persistencia.veiculomodel')),
            ],
            options={
                'ordering': ['data', 'saida'],
                'indexes': [models.Index(fields=['veiculo', 'data'], name='persistenci_veiculo_524853_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('retorno__gt', models.F('saida'))), name='retorno_posterior_a_saida')],
            },
        ),
    ]
