# Generated by Django 5.2.18 on 2026-10-08 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("persistencia", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservamodel",
            options={
                "ordering": ["data", "saida"],
                "verbose_name": "reserva",
                "verbose_name_plural": "reservas",
            },
        ),
        migrations.AlterModelOptions(
            name="veiculomodel",
            options={
                "ordering": ["codigo"],
                "verbose_name": "veículo",
                "verbose_name_plural": "veículos",
            },
        ),
    ]
