# Generated by Django 5.2.18 on 2026-10-08 23:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistencia", "0002_nomes_no_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="ColaboradorModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telefone", models.CharField(blank=True, max_length=20)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "colaborador",
                "verbose_name_plural": "colaboradores",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="SetorModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=80, unique=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "setor",
                "verbose_name_plural": "setores",
                "ordering": ["nome"],
            },
        ),
        migrations.AddField(
            model_name="reservamodel",
            name="atualizada_em",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="reservamodel",
            name="cancelada_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reservamodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("CONFIRMADA", "Confirmada"),
                    ("CANCELADA", "Cancelada"),
                    ("CONCLUIDA", "Concluída"),
                ],
                default="CONFIRMADA",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="veiculomodel",
            name="ativo",
            field=models.BooleanField(
                default=True,
                help_text="Desmarque quando o veículo estiver fora de operação.",
            ),
        ),
        migrations.AddField(
            model_name="veiculomodel",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="veiculomodel",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="veiculomodel",
            name="modelo",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="veiculomodel",
            name="placa",
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="reservamodel",
            name="colaborador",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservas",
                to="persistencia.colaboradormodel",
            ),
        ),
        migrations.AddConstraint(
            model_name="reservamodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("passageiros__gte", 1)),
                name="ao_menos_um_passageiro",
            ),
        ),
        migrations.AddConstraint(
            model_name="reservamodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["CONFIRMADA", "CANCELADA", "CONCLUIDA"])
                ),
                name="status_valido",
            ),
        ),
        migrations.AddField(
            model_name="colaboradormodel",
            name="setor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="colaboradores",
                to="persistencia.setormodel",
            ),
        ),
        migrations.AddConstraint(
            model_name="colaboradormodel",
            constraint=models.UniqueConstraint(
                fields=("nome", "setor"), name="colaborador_unico_no_setor"
            ),
        ),
    ]
