from datetime import date
from typing import Protocol

from core.domain.entidades import CategoriaVeiculo, Reserva, Veiculo


class VeiculoRepository(Protocol):
    def listar(self) -> list[Veiculo]: ...

    def listar_por_categoria(self, categoria: CategoriaVeiculo) -> list[Veiculo]: ...

    def obter(self, codigo: str) -> Veiculo | None: ...

    def salvar(self, veiculo: Veiculo) -> Veiculo: ...


class ReservaRepository(Protocol):
    def listar(self, data: date | None = None) -> list[Reserva]: ...

    def listar_do_veiculo_na_data(self, codigo: str, data: date) -> list[Reserva]: ...

    def obter(self, reserva_id: int) -> Reserva | None: ...

    def salvar(self, reserva: Reserva) -> Reserva: ...

    def excluir(self, reserva_id: int) -> bool: ...
